// <auto-generated />
using BTLNhapMonCNPM.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BTLNhapMonCNPM.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BTLNhapMonCNPM.Models.LoaiSanPham", b =>
                {
                    b.Property<int>("iMaLoaiSP")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("iMaLoaiSP"));

                    b.Property<string>("sTenLoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("iMaLoaiSP");

                    b.ToTable("tblLoaiSanPham");
                });

            modelBuilder.Entity("BTLNhapMonCNPM.Models.SanPham", b =>
                {
                    b.Property<int>("iMaSP")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("iMaSP"));

                    b.Property<decimal>("fGiaBan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("fGiaNhap")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("iMaLoaiSP")
                        .HasColumnType("int");

                    b.Property<int>("iMaNCC")
                        .HasColumnType("int");

                    b.Property<int>("iSoLuong")
                        .HasColumnType("int");

                    b.Property<string>("sCachSuDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sDangThuoc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sDieuKienBaoQuan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sDonViTinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sImageThuoc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("iMaSP");

                    b.ToTable("tblSanPham");
                });
#pragma warning restore 612, 618
        }
    }
}
