// <auto-generated />
using System;
using BTLNhapMonCNPM.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BTLNhapMonCNPM.Migrations
{
    [DbContext(typeof(PharmacyDbContext))]
    partial class PharmacyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BTLNhapMonCNPM.Models.TblHoaDon", b =>
                {
                    b.Property<int>("IMaHd")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("iMaHD");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IMaHd"));

                    b.Property<DateTime>("DThoiGian")
                        .HasColumnType("datetime")
                        .HasColumnName("dThoiGian");

                    b.Property<decimal>("FTongGiaTri")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("fTongGiaTri");

                    b.Property<int?>("IMaKh")
                        .HasColumnType("int")
                        .HasColumnName("iMaKH");

                    b.Property<string>("SGhiChu")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("sGhiChu");

                    b.HasKey("IMaHd")
                        .HasName("PK__tblHoaDo__F20ABED0701FF6C3");

                    b.HasIndex("IMaKh");

                    b.ToTable("tblHoaDon");
                });

            modelBuilder.Entity("BTLNhapMonCNPM.Models.TblKhachHang", b =>
                {
                    b.Property<int>("IMaKh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("iMaKH");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IMaKh"));

                    b.Property<DateTime?>("DNgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("dNgayTao")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("SEmail")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("sEmail");

                    b.Property<string>("SHoTen")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("sHoTen");

                    b.Property<string>("SMatKhau")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("sMatKhau");

                    b.Property<string>("SSdt")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("sSDT");

                    b.Property<string>("STenDangNhap")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("sTenDangNhap");

                    b.HasKey("IMaKh")
                        .HasName("PK__tblKhach__F20AA50860D00D03");

                    b.HasIndex(new[] { "SEmail" }, "UQ__tblKhach__07DACB08679F8ED0")
                        .IsUnique()
                        .HasFilter("[sEmail] IS NOT NULL");

                    b.HasIndex(new[] { "STenDangNhap" }, "UQ__tblKhach__2584CE9E610A2FA1")
                        .IsUnique();

                    b.ToTable("tblKhachHang");
                });

            modelBuilder.Entity("BTLNhapMonCNPM.Models.TblKhieuNai", b =>
                {
                    b.Property<int>("IMaKn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("iMaKN");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IMaKn"));

                    b.Property<bool>("BDaGiaiQuyet")
                        .HasColumnType("bit")
                        .HasColumnName("bDaGiaiQuyet");

                    b.Property<DateTime>("DThoiGian")
                        .HasColumnType("datetime")
                        .HasColumnName("dThoiGian");

                    b.Property<int?>("IMaKh")
                        .HasColumnType("int")
                        .HasColumnName("iMaKH");

                    b.Property<string>("SNguyenNhan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("sNguyenNhan");

                    b.HasKey("IMaKn")
                        .HasName("PK__tblKhieu__F20AA502DF963DC6");

                    b.HasIndex("IMaKh");

                    b.ToTable("tblKhieuNai");
                });

            modelBuilder.Entity("BTLNhapMonCNPM.Models.TblLoSanPham", b =>
                {
                    b.Property<int>("ILoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("iLoId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ILoId"));

                    b.Property<DateOnly>("DNgayHetHan")
                        .HasColumnType("date")
                        .HasColumnName("dNgayHetHan");

                    b.Property<DateOnly>("DNgayNhap")
                        .HasColumnType("date")
                        .HasColumnName("dNgayNhap");

                    b.Property<DateOnly>("DNgaySanXuat")
                        .HasColumnType("date")
                        .HasColumnName("dNgaySanXuat");

                    b.Property<decimal>("FGiaNhap")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("fGiaNhap");

                    b.Property<int>("IDonNhapId")
                        .HasColumnType("int")
                        .HasColumnName("iDonNhapId");

                    b.Property<int>("ISanPhamId")
                        .HasColumnType("int")
                        .HasColumnName("iSanPhamId");

                    b.Property<int>("ISoLuongNhap")
                        .HasColumnType("int")
                        .HasColumnName("iSoLuongNhap");

                    b.Property<int>("ISoLuongTon")
                        .HasColumnType("int")
                        .HasColumnName("iSoLuongTon");

                    b.Property<string>("SDonViTinh")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("sDonViTinh");

                    b.HasKey("ILoId")
                        .HasName("PK__tblLoSan__D6EA297DB9308BBB");

                    b.HasIndex("IDonNhapId");

                    b.HasIndex("ISanPhamId");

                    b.ToTable("tblLoSanPham");
                });

            modelBuilder.Entity("BTLNhapMonCNPM.Models.TblLoaiSanPham", b =>
                {
                    b.Property<int>("IMaLoaiSp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("iMaLoaiSP");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IMaLoaiSp"));

                    b.Property<string>("STenLoai")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("sTenLoai");

                    b.HasKey("IMaLoaiSp")
                        .HasName("PK__tblLoaiS__4B6603B6C6064CBF");

                    b.ToTable("tblLoaiSanPham");
                });

            modelBuilder.Entity("BTLNhapMonCNPM.Models.TblNhaCungCap", b =>
                {
                    b.Property<int>("IMaNcc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("iMaNCC");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IMaNcc"));

                    b.Property<byte[]>("BChungChi")
                        .IsRequired()
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("bChungChi");

                    b.Property<string>("SDiaChi")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("sDiaChi");

                    b.Property<string>("SEmail")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("sEmail");

                    b.Property<string>("SSdt")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("sSDT");

                    b.Property<string>("STenNcc")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("sTenNCC");

                    b.HasKey("IMaNcc")
                        .HasName("PK__tblNhaCu__204A73DC644A75C9");

                    b.ToTable("tblNhaCungCap");
                });

            modelBuilder.Entity("BTLNhapMonCNPM.Models.TblNhanVien", b =>
                {
                    b.Property<int>("IMaNv")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("iMaNV");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IMaNv"));

                    b.Property<DateOnly>("DNgayVaoLam")
                        .HasColumnType("date")
                        .HasColumnName("dNgayVaoLam");

                    b.Property<decimal>("FHeSoLuong")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("fHeSoLuong");

                    b.Property<decimal>("FLuongCb")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("fLuongCB");

                    b.Property<string>("SChucVu")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("sChucVu");

                    b.Property<string>("SHoTen")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("sHoTen");

                    b.Property<string>("SMatKhau")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("sMatKhau");

                    b.Property<string>("STenDangNhap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("sTenDangNhap");

                    b.HasKey("IMaNv")
                        .HasName("PK__tblNhanV__F20A8D79D2CAB3C0");

                    b.HasIndex(new[] { "STenDangNhap" }, "UQ__tblNhanV__2584CE9E1967B839")
                        .IsUnique();

                    b.ToTable("tblNhanVien");
                });

            modelBuilder.Entity("BTLNhapMonCNPM.Models.TblNhapHang", b =>
                {
                    b.Property<int>("IMaNh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("iMaNH");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IMaNh"));

                    b.Property<DateTime>("DNgayTao")
                        .HasColumnType("datetime")
                        .HasColumnName("dNgayTao");

                    b.Property<double>("FTongTien")
                        .HasColumnType("float")
                        .HasColumnName("fTongTien");

                    b.Property<int>("IMaNcc")
                        .HasColumnType("int")
                        .HasColumnName("iMaNCC");

                    b.Property<int?>("IMaNv")
                        .HasColumnType("int")
                        .HasColumnName("iMaNV");

                    b.HasKey("IMaNh")
                        .HasName("PK__tblNhapH__F20A8D6B5A0E4776");

                    b.HasIndex("IMaNcc");

                    b.HasIndex("IMaNv");

                    b.ToTable("tblNhapHang");
                });

            modelBuilder.Entity("BTLNhapMonCNPM.Models.TblSanPham", b =>
                {
                    b.Property<int>("IMaSp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("iMaSP");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IMaSp"));

                    b.Property<bool>("BBietTru")
                        .HasColumnType("bit")
                        .HasColumnName("bBietTru");

                    b.Property<bool>("BCanKeDon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("bCanKeDon");

                    b.Property<bool>("BThuHoi")
                        .HasColumnType("bit")
                        .HasColumnName("bThuHoi");

                    b.Property<decimal>("FGiaBan")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("fGiaBan");

                    b.Property<decimal>("FGiaNhap")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("fGiaNhap");

                    b.Property<int>("IMaLoaiSp")
                        .HasColumnType("int")
                        .HasColumnName("iMaLoaiSP");

                    b.Property<int>("IMaNcc")
                        .HasColumnType("int")
                        .HasColumnName("iMaNCC");

                    b.Property<int?>("ISoLuong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("iSoLuong");

                    b.Property<string>("SCachSuDung")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("sCachSuDung");

                    b.Property<string>("SDangThuoc")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("sDangThuoc");

                    b.Property<string>("SDieuKienBaoQuan")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("sDieuKienBaoQuan");

                    b.Property<string>("SDonViTinh")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("sDonViTinh");

                    b.Property<string>("SHanSuDung")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("sHanSuDung");

                    b.Property<string>("SImageThuoc")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("sImageThuoc");

                    b.Property<string>("STen")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("sTen");

                    b.HasKey("IMaSp")
                        .HasName("PK__tblSanPh__F20A661E1F6C4D7D");

                    b.HasIndex("IMaLoaiSp");

                    b.HasIndex("IMaNcc");

                    b.ToTable("tblSanPham");
                });

            modelBuilder.Entity("BTLNhapMonCNPM.Models.TblThuocKeDon", b =>
                {
                    b.Property<int>("IMaTkd")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("iMaTKD");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IMaTkd"));

                    b.Property<DateTime>("DNgayTao")
                        .HasColumnType("datetime")
                        .HasColumnName("dNgayTao");

                    b.Property<int?>("IMaKh")
                        .HasColumnType("int")
                        .HasColumnName("iMaKH");

                    b.Property<int>("IMaNv")
                        .HasColumnType("int")
                        .HasColumnName("iMaNV");

                    b.Property<string>("SGhiChu")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("sGhiChu");

                    b.HasKey("IMaTkd")
                        .HasName("PK__tblThuoc__22CA58456196E352");

                    b.HasIndex("IMaKh");

                    b.HasIndex("IMaNv");

                    b.ToTable("tblThuocKeDon");
                });

            modelBuilder.Entity("BTLNhapMonCNPM.Models.TblHoaDon", b =>
                {
                    b.HasOne("BTLNhapMonCNPM.Models.TblKhachHang", "IMaKhNavigation")
                        .WithMany("TblHoaDons")
                        .HasForeignKey("IMaKh")
                        .HasConstraintName("FK__tblHoaDon__iMaKH__49C3F6B7");

                    b.Navigation("IMaKhNavigation");
                });

            modelBuilder.Entity("BTLNhapMonCNPM.Models.TblKhieuNai", b =>
                {
                    b.HasOne("BTLNhapMonCNPM.Models.TblKhachHang", "IMaKhNavigation")
                        .WithMany("TblKhieuNais")
                        .HasForeignKey("IMaKh")
                        .HasConstraintName("FK__tblKhieuN__iMaKH__4CA06362");

                    b.Navigation("IMaKhNavigation");
                });

            modelBuilder.Entity("BTLNhapMonCNPM.Models.TblLoSanPham", b =>
                {
                    b.HasOne("BTLNhapMonCNPM.Models.TblNhapHang", "IDonNhap")
                        .WithMany("TblLoSanPhams")
                        .HasForeignKey("IDonNhapId")
                        .IsRequired()
                        .HasConstraintName("FK__tblLoSanP__iDonN__59063A47");

                    b.HasOne("BTLNhapMonCNPM.Models.TblSanPham", "ISanPham")
                        .WithMany("TblLoSanPhams")
                        .HasForeignKey("ISanPhamId")
                        .IsRequired()
                        .HasConstraintName("FK__tblLoSanP__iSanP__5812160E");

                    b.Navigation("IDonNhap");

                    b.Navigation("ISanPham");
                });

            modelBuilder.Entity("BTLNhapMonCNPM.Models.TblNhapHang", b =>
                {
                    b.HasOne("BTLNhapMonCNPM.Models.TblNhaCungCap", "IMaNccNavigation")
                        .WithMany("TblNhapHangs")
                        .HasForeignKey("IMaNcc")
                        .IsRequired()
                        .HasConstraintName("FK__tblNhapHa__iMaNC__5070F446");

                    b.HasOne("BTLNhapMonCNPM.Models.TblNhanVien", "IMaNvNavigation")
                        .WithMany("TblNhapHangs")
                        .HasForeignKey("IMaNv")
                        .HasConstraintName("FK__tblNhapHa__iMaNV__4F7CD00D");

                    b.Navigation("IMaNccNavigation");

                    b.Navigation("IMaNvNavigation");
                });

            modelBuilder.Entity("BTLNhapMonCNPM.Models.TblSanPham", b =>
                {
                    b.HasOne("BTLNhapMonCNPM.Models.TblLoaiSanPham", "IMaLoaiSpNavigation")
                        .WithMany("TblSanPhams")
                        .HasForeignKey("IMaLoaiSp")
                        .IsRequired()
                        .HasConstraintName("FK__tblSanPha__iMaLo__46E78A0C");

                    b.HasOne("BTLNhapMonCNPM.Models.TblNhaCungCap", "IMaNccNavigation")
                        .WithMany("TblSanPhams")
                        .HasForeignKey("IMaNcc")
                        .IsRequired()
                        .HasConstraintName("FK__tblSanPha__iMaNC__45F365D3");

                    b.Navigation("IMaLoaiSpNavigation");

                    b.Navigation("IMaNccNavigation");
                });

            modelBuilder.Entity("BTLNhapMonCNPM.Models.TblThuocKeDon", b =>
                {
                    b.HasOne("BTLNhapMonCNPM.Models.TblKhachHang", "IMaKhNavigation")
                        .WithMany("TblThuocKeDons")
                        .HasForeignKey("IMaKh")
                        .HasConstraintName("FK__tblThuocK__iMaKH__534D60F1");

                    b.HasOne("BTLNhapMonCNPM.Models.TblNhanVien", "IMaNvNavigation")
                        .WithMany("TblThuocKeDons")
                        .HasForeignKey("IMaNv")
                        .IsRequired()
                        .HasConstraintName("FK__tblThuocK__iMaNV__5441852A");

                    b.Navigation("IMaKhNavigation");

                    b.Navigation("IMaNvNavigation");
                });

            modelBuilder.Entity("BTLNhapMonCNPM.Models.TblKhachHang", b =>
                {
                    b.Navigation("TblHoaDons");

                    b.Navigation("TblKhieuNais");

                    b.Navigation("TblThuocKeDons");
                });

            modelBuilder.Entity("BTLNhapMonCNPM.Models.TblLoaiSanPham", b =>
                {
                    b.Navigation("TblSanPhams");
                });

            modelBuilder.Entity("BTLNhapMonCNPM.Models.TblNhaCungCap", b =>
                {
                    b.Navigation("TblNhapHangs");

                    b.Navigation("TblSanPhams");
                });

            modelBuilder.Entity("BTLNhapMonCNPM.Models.TblNhanVien", b =>
                {
                    b.Navigation("TblNhapHangs");

                    b.Navigation("TblThuocKeDons");
                });

            modelBuilder.Entity("BTLNhapMonCNPM.Models.TblNhapHang", b =>
                {
                    b.Navigation("TblLoSanPhams");
                });

            modelBuilder.Entity("BTLNhapMonCNPM.Models.TblSanPham", b =>
                {
                    b.Navigation("TblLoSanPhams");
                });
#pragma warning restore 612, 618
        }
    }
}
